FROM wordpress

#xdebug
RUN pecl install xdebug
RUN docker-php-ext-enable xdebug
COPY config/xdebug.ini /tmp/
RUN cat /tmp/xdebug.ini >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && rm /tmp/xdebug.ini

#wp-cli
RUN curl -o /bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x /bin/wp
